go_import_path: go.fraixed.es/onepagestaticsite
language: go

go:
  - 1.12.x
  - 1.11.x
  - tip

env:
  - GO111MODULE=on LINT=true COVERAGE=true
  - GO111MODULE=on

matrix:
  exclude:
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.11.x
      env: GO111MODULE=on LINT=true COVERAGE=true
    - go: tip
      env: GO111MODULE=on LINT=true COVERAGE=true
  allow_failures:
    - go: tip
      env: GO111MODULE=on

before_install:
  - make .go-tools-install-ci

  # Install goveralls, Go integration for Coveralls.io.
  - go get -u github.com/mattn/goveralls

script:
  - make ci

notifications:
  email: false
